### ISSUE TITLE
Cannot find module '@coreui/coreui/dist/js/coreui-utilities'

### ISSUE THREAD

**Issue by safwanazam90** [coreui/coreui-free-angular-admin-template#244]
After update from 2.11.2 to 4.3.1, my project cannot find the module. Is it depreciated?

**Comment by xidedix** [comment]
@safwanazam90 
coreui-utilities has been moved to the separate package
use `@coreui/utils` - the latest version is `2.0.0`

```bash
npm install @coreui/utils@2.0.0
```

import looks like:
```ts
import { getStyle, hexToRgba } from '@coreui/utils
```
